# Reranker selection and hyperparameters
# type: qformer | bge_text | cross_encoder

# ------------------------------------------
# [Option 1] Q-former
# ------------------------------------------
type: qformer
qformer_device: cuda:0
qformer_batch: 32
alpha_1: 0.5
alpha_2: 0.5

# ------------------------------------------
# [Option 2] BGE Reranker
# ------------------------------------------
# type: bge_text
# model_name: BAAI/bge-reranker-large
# bge_device: cuda:3
# torch_dtype: float16
# batch_size: 16
# truncate_len: 512
# alpha_1: 0.5   # retrieval score weight
# alpha_2: 0.5   # BGE score weight

# ------------------------------------------
# [Option 3] ms-marco-electra Cross-Encoder
# ------------------------------------------
# type: cross_encoder
# model_name: cross-encoder/ms-marco-electra-base
# ce_device: cuda:3
# torch_dtype: float16
# batch_size: 8
# truncate_len: 512
# alpha_1: 0.5   # retrieval score weight
# alpha_2: 0.5   # cross-encoder score weight
